version: "3.9"
services:
  api:
    build: api/.
    ports:
      - "9000:9000"
    environment:
      DB_HOST: mongo
    depends_on:
      - "mongo" 
  client:
    build: client/.
    ports:
      - "8080:8080"
    depends_on:
      - "api" 

  mongo:
    image: "mongo:5.0"
    ports:
      - "27017:27017"
  nginx:
    image: "nginx:1.21.6"
    network_mode: host
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "client" 
      - "api" 

