version: "3.9"
services:
  api:
    build: api/.
    ports:
      - "9000:9000"
    environment:
      DB_HOST: mongo
    depends_on:
      - "mongo" 

  web:
    image: "anacarrillo/app-travel_client:latest"
    ports:
      - "8080:8080"
    volumes:
      - ./docker/client/nginx.conf:/etc/nginx/nginx.conf

  mongo:
    image: "mongo:5.0"
    ports:
      - "27017:27017"
  nginx:
    image: "nginx:1.21.6"
    network_mode: host
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "web" 
      - "api" 

